### ISSUE TITLE
Migrating to phergie/phergie-irc-bot-react-development

### ISSUE THREAD

**Issue by svpernova09** [phergie/plugin-http#1]
```
        "vectorface/dunit": "^2.0",
        "squizlabs/php_codesniffer": "^1.5.3"
```

These 2 plugins don't exist yet in our dev package, if I add them would there be any road block to this plugin using https://github.com/phergie/phergie-irc-bot-react-development?

**Comment by WyriHaximus** [comment]
No not at all, this makes perfect sense to me :+1: . I'll go and update this package
