### ISSUE TITLE
Cannot use $this as parameter

### ISSUE THREAD

**Issue by sitedyno** [phergie/plugin-http#7]
I'm getting the fatal error below when trying to run this repo on php 7.0.18 https://github.com/sitedyno/phergie-sitedyno
```
PHP Fatal error:  Cannot use $this as parameter in /home/durkon/phergie/vendor/react/http-client/src/Request.php on line 94
PHP Stack trace:
PHP   1. {main}() /home/durkon/phergie/vendor/phergie/phergie-irc-bot-react/bin/phergie:0
PHP   2. Phergie\Irc\Bot\React\Bot->run() /home/durkon/phergie/vendor/phergie/phergie-irc-bot-react/bin/phergie:28
PHP   3. Phergie\Irc\Client\React\Client->run() /home/durkon/phergie/vendor/phergie/phergie-irc-bot-react/src/Bot.php:237
PHP   4. React\EventLoop\StreamSelectLoop->run() /home/durkon/phergie/vendor/phergie/phergie-irc-client-react/src/Client.php:731
PHP   5. React\EventLoop\Tick\FutureTickQueue->tick() /home/durkon/phergie/vendor/react/event-loop/StreamSelectLoop.php:175
PHP   6. call_user_func:{/home/durkon/phergie/vendor/react/event-loop/Tick/FutureTickQueue.php:45}() /home/durkon/phergie/vendor/react/event-loop/Tick/FutureTickQueue.php:45
PHP   7. WyriHaximus\React\Guzzle\HttpClient\Request->WyriHaximus\React\Guzzle\HttpClient\{closure}() /home/durkon/phergie/vendor/react/event-loop/Tick/FutureTickQueue.php:45
PHP   8. WyriHaximus\React\Guzzle\HttpClient\Request->setupRequest() /home/durkon/phergie/vendor/wyrihaximus/react-guzzle-http-client/src/Request.php:181
PHP   9. React\HttpClient\Client->request() /home/durkon/phergie/vendor/wyrihaximus/react-guzzle-http-client/src/Request.php:203
PHP  10. spl_autoload_call() /home/durkon/phergie/vendor/react/http-client/src/Client.php:23
PHP  11. Composer\Autoload\ClassLoader->loadClass() /home/durkon/phergie/vendor/react/http-client/src/Client.php:23
PHP  12. Composer\Autoload\includeFile() /home/durkon/phergie/vendor/composer/ClassLoader.php:301
```
It should be pretty simple to clone the repo and try it (be sure to use the sitedyno version of the config files). You don't need any API keys, just use !bofh 

If that's too much trouble let me know and I will try to arrange something simpler.

I THINK that getting a version bump for wyrihaximus/react-guzzle-ring will fix this issue.

Thanks.

**Comment by WyriHaximus** [comment]
Hey @sitedyno, the issue is actually a lot simpler, while looking through your [`composer.lock`](https://github.com/sitedyno/phergie-sitedyno/blob/sitedyno/composer.lock#L2056) I found that you're locked to `react/http-client` `v0.4.8`, there has been a [fix](https://github.com/reactphp/http-client/commit/123cd86d9ae0734ac29bb75c8e13a60ef2cf08a1) in `react/http-client` [`v0.4.9`](https://github.com/reactphp/http-client/releases/tag/v0.4.9) that solves this issue for you. A simple `composer update react/http-client` should fix it for you.

**Comment by sitedyno** [comment]
Works for me. Thanks for taking a look :)

**Comment by WyriHaximus** [comment]
No problem, and thank you for committing your `composer.lock`, that made things very simple
