### ISSUE TITLE
No longer possible to pass headers?

### ISSUE THREAD

**Issue by sitedyno** [phergie/plugin-http#8]
Seems that ability was removed here? https://github.com/phergie/plugin-http/commit/ffd2b6c60d923300227e4f4f2611e001cbe4212d#diff-f7fcf01b75ab0236c970de527853c3abL106

Or am I being dumb per usual? 😁

**Comment by WyriHaximus** [comment]
@sitedyno seems you're right, I'll PR a fix later today, thank you for reporting :+1:

**Comment by sitedyno** [comment]
Closing since pull request is up.
